import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react';
import { StaticImageData } from 'next/image';

// Import components
import Header from '@/components/Header';
import ProfileSection from '@/components/ProfileSection';
import SkillsSection from '@/components/SkillsSection';
import PortfolioSection from '@/components/PortfolioSection';
import LoadingScreen from '@/components/LoadingScreen';

// Import translations
import { translations } from '@/utils/translations';

// Import project images
import { projectImages, projectMainImages, projectDescriptionHeaders, projectDescriptions } from '@/utils/projectData';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [language, setLanguage] = useState<'id' | 'en'>('en');
  const [loading, setLoading] = useState(true);
  const [fadeOut, setFadeOut] = useState(false);

  // Helper function to get translated text
  const t = (key: keyof typeof translations[keyof typeof translations]) => translations[language][key];

  useEffect(() => {
    const timer = setTimeout(() => {
      setFadeOut(true);
      setTimeout(() => {
        setLoading(false);
      }, 1000); // Time for fade out effect
    }, 1200);

    return () => clearTimeout(timer);
  }, []);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white dark:bg-gray-900 min-h-screen'> 
        {/* Loading Screen */}
        <LoadingScreen 
          loading={loading} 
          fadeOut={fadeOut} 
          translations={translations} 
          language={language} 
        />
        
        {/* Header with Navigation */}
        <Header 
          darkMode={darkMode} 
          setDarkMode={setDarkMode} 
          language={language} 
          setLanguage={setLanguage} 
          translations={translations} 
        />
        
        {/* Profile Section */}
        <ProfileSection 
          translations={translations} 
          language={language} 
        />
        
        {/* Skills Section */}
        <SkillsSection 
          translations={translations} 
          language={language} 
        />
        
        {/* Portfolio Section */}
        <PortfolioSection 
          translations={translations} 
          language={language} 
          projectImages={projectImages} 
          projectMainImages={projectMainImages} 
          projectDescriptionHeaders={projectDescriptionHeaders} 
          projectDescriptions={projectDescriptions} 
        />
      </main>
    </div>
  );
}